# This file was generated by GoReleaser. DO NOT EDIT.
cask "eta" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "3ddfd5b214b30b10514608a1b92a28641f0f4497f9e781ea8de7c4aee3187317"
      url "https://github.com/bancsdan/eta/releases/download/v#{version}/eta_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "cac57c77a8131f33fdd483d11a639140222b86f2029b069ddbdc2b6f9cc3b06f"
      url "https://github.com/bancsdan/eta/releases/download/v#{version}/eta_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "97393f62118ffc57989c5254059b9e943dcfa747bf35b05bc7a6b3d07cb2ec5f"
      url "https://github.com/bancsdan/eta/releases/download/v#{version}/eta_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f3bdec344581a421aa40c8f17790bfaeef92f600ac9bd209c113e0a703be12af"
      url "https://github.com/bancsdan/eta/releases/download/v#{version}/eta_#{version}_linux_amd64.tar.gz"
    end
  end

  name "eta"
  desc "Next public-transport departures at a stop, from your terminal"
  homepage "https://github.com/bancsdan/eta"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "eta"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/eta"]
    end
  end

  # No zap stanza required
end
