# This file was generated by GoReleaser. DO NOT EDIT.
cask "eta" do
  version "0.2.2"

  on_macos do
    on_arm do
      sha256 "5cea3ca3396790c3a9cb8b1b8d78fbee4a54facc11699b754cdb31b730bd3495"
      url "https://github.com/bancsdan/eta/releases/download/v#{version}/eta_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "00079e6894ea8e7d8d24061f5a097bd0bdab419483f553e897f8e36971d1b0c2"
      url "https://github.com/bancsdan/eta/releases/download/v#{version}/eta_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "11d045cb676d650f4b590bd7257fef40963dc9d7324a537dd2daa9b234769e9f"
      url "https://github.com/bancsdan/eta/releases/download/v#{version}/eta_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1c586652f8613240779323baa4eedf5de81bebb392e9e2019d9e2d6782e83055"
      url "https://github.com/bancsdan/eta/releases/download/v#{version}/eta_#{version}_linux_amd64.tar.gz"
    end
  end

  name "eta"
  desc "Next public-transport departures at a stop, from your terminal"
  homepage "https://github.com/bancsdan/eta"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "eta"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/eta"]
    end
  end

  # No zap stanza required
end
