# This file was generated by GoReleaser. DO NOT EDIT.
cask "eta" do
  version "0.2.1"

  on_macos do
    on_arm do
      sha256 "2ddbc0b75364a63bd16baeb5b143f267159875c0e7873ab30652691f0263c29d"
      url "https://github.com/bancsdan/eta/releases/download/v#{version}/eta_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a839da5c05bd420d3fbcc847270f6afa5c095a83f01c65353d3f74cd0ec86269"
      url "https://github.com/bancsdan/eta/releases/download/v#{version}/eta_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f42954adcba949ef5fa9ef4d08c9ae344241e6a766c3037a24aebcf5c8144b25"
      url "https://github.com/bancsdan/eta/releases/download/v#{version}/eta_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9f4ce2393d0d701147cb73573e8701b10f4e2593a399bf6fe48035daa6cd63a0"
      url "https://github.com/bancsdan/eta/releases/download/v#{version}/eta_#{version}_linux_amd64.tar.gz"
    end
  end

  name "eta"
  desc "Next public-transport departures at a stop, from your terminal"
  homepage "https://github.com/bancsdan/eta"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "eta"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/eta"]
    end
  end

  # No zap stanza required
end
